"""
Disposable / temporary email domain blocklist and domain validation.

Used to prevent trial abuse by:
1. Rejecting registrations from throwaway email providers
2. Verifying that the email domain actually has mail servers (MX records)
"""

import dns.resolver


# Well-known domains that we always allow (skip DNS lookup for speed)
_TRUSTED_DOMAINS: set[str] = {
    "gmail.com", "googlemail.com", "outlook.com", "hotmail.com",
    "live.com", "msn.com", "yahoo.com", "yahoo.com.br", "icloud.com",
    "me.com", "mac.com", "aol.com", "protonmail.com", "proton.me",
    "zoho.com", "uol.com.br", "bol.com.br", "terra.com.br",
    "ig.com.br", "globo.com", "outlook.com.br",
}

# Comprehensive list of known disposable email domains.
# Sources: github.com/disposable-email-domains, community lists.
DISPOSABLE_DOMAINS: set[str] = {
    # ── Popular disposable services ──
    "mailinator.com",
    "guerrillamail.com",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamail.de",
    "grr.la",
    "guerrillamailblock.com",
    "tempmail.com",
    "temp-mail.org",
    "temp-mail.io",
    "throwaway.email",
    "throwaway.com",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "sharklasers.com",
    "dispostable.com",
    "trashmail.com",
    "trashmail.me",
    "trashmail.net",
    "trashmail.org",
    "trashymail.com",
    "trashymail.net",
    "mailnesia.com",
    "maildrop.cc",
    "discard.email",
    "discardmail.com",
    "discardmail.de",
    "fakeinbox.com",
    "fakemail.net",
    "mailcatch.com",
    "mailexpire.com",
    "mailnator.com",
    "mailscrap.com",
    "meltmail.com",
    "mintemail.com",
    "mt2015.com",
    "mytemp.email",
    "mytrashmail.com",
    "nospam.ze.tc",
    "no-spam.ws",
    "owlpic.com",
    "proxymail.eu",
    "rcpt.at",
    "trash-mail.at",
    "trashmail.at",
    "trbvm.com",
    "uggsrock.com",
    "wegwerfmail.de",
    "wegwerfmail.net",
    "wegwerfmail.org",
    "wh4f.org",
    "yolanda.dev",
    "zehnminutenmail.de",
    "10minutemail.com",
    "10minutemail.net",
    "10minutemail.org",
    "10minutemail.de",
    "10mail.org",
    "20minutemail.com",
    "20minutemail.it",
    "anonbox.net",
    "binkmail.com",
    "bobmail.info",
    "burnthismail.com",
    "buyusedlibrarybooks.org",
    "byom.de",
    "cashette.com",
    "chogmail.com",
    "coolimpool.org",
    "cosmorph.com",
    "courriel.fr.nf",
    "crapmail.org",
    "dandikmail.com",
    "deadaddress.com",
    "despammed.com",
    "devnullmail.com",
    "dfgh.net",
    "digitalsanctuary.com",
    "disposableaddress.com",
    "disposableemailaddresses.emailmiser.com",
    "disposableinbox.com",
    "dispose.it",
    "dm.w3internet.co.uk",
    "dodgeit.com",
    "dodgit.com",
    "dodgit.org",
    "dontreg.com",
    "dontsendmespam.de",
    "drdrb.net",
    "dump-email.info",
    "dumpanyjunk.com",
    "dumpyemail.com",
    "e4ward.com",
    "easytrashmail.com",
    "einmalmail.de",
    "emailgo.de",
    "emailias.com",
    "emailigo.de",
    "emailinfive.com",
    "emaillime.com",
    "emailmiser.com",
    "emailproxsy.com",
    "emailsensei.com",
    "emailtemporario.com.br",
    "emailwarden.com",
    "emailx.at.hm",
    "emailxfer.com",
    "emz.net",
    "enterto.com",
    "ephemail.net",
    "etranquil.com",
    "etranquil.net",
    "etranquil.org",
    "evopo.com",
    "explodemail.com",
    "express.net.ua",
    "eyepaste.com",
    "fastacura.com",
    "filzmail.com",
    "fixmail.tk",
    "flyspam.com",
    "frapmail.com",
    "front14.org",
    "fux0ringduh.com",
    "garliclife.com",
    "get1mail.com",
    "get2mail.fr",
    "getairmail.com",
    "getmails.eu",
    "getonemail.com",
    "getonemail.net",
    "ghosttexter.de",
    "girlsundertheinfluence.com",
    "gishpuppy.com",
    "goemailgo.com",
    "gotmail.net",
    "gotmail.org",
    "gotti.otherinbox.com",
    "great-host.in",
    "greensloth.com",
    "haltospam.com",
    "harakirimail.com",
    "hat-gansen.de",
    "hatespam.org",
    "herp.in",
    "hidemail.de",
    "hidzz.com",
    "hotpop.com",
    "ieatspam.eu",
    "ieatspam.info",
    "imails.info",
    "inbax.tk",
    "inbox.si",
    "inboxalias.com",
    "inboxclean.com",
    "inboxclean.org",
    "incognitomail.com",
    "incognitomail.net",
    "incognitomail.org",
    "insorg-mail.info",
    "ipoo.org",
    "irish2me.com",
    "iwi.net",
    "jetable.com",
    "jetable.fr.nf",
    "jetable.net",
    "jetable.org",
    "jnxjn.com",
    "jourrapide.com",
    "jsrsolutions.com",
    "kasmail.com",
    "kaspop.com",
    "keepmymail.com",
    "killmail.com",
    "killmail.net",
    "kir.ch.tc",
    "klassmaster.com",
    "klassmaster.net",
    "klzlk.com",
    "koszmail.pl",
    "kurzepost.de",
    "lackmail.net",
    # "lavabit.com" — removido: serviço legítimo encerrado em 2013, não descartável
    "letmeinonthis.com",
    "lhsdv.com",
    "lifebyfood.com",
    "link2mail.net",
    "litedrop.com",
    "lol.ovpn.to",
    "lookugly.com",
    "lopl.co.cc",
    "lortemail.dk",
    "lroid.com",
    "lukop.dk",
    "m21.cc",
    "mail-hierarchie.de",
    "mail-temporaire.fr",
    "mail.by",
    "mail.mezimages.net",
    "mail.zp.ua",
    "mail2rss.org",
    "mail333.com",
    "mail4trash.com",
    "mailbidon.com",
    "mailblocks.com",
    "mailbox52.ga",
    "mailbox80.biz",
    "mailbox92.biz",
    "mailbucket.org",
    "mailcat.biz",
    "maileater.com",
    "mailexpire.com",
    "mailfa.tk",
    "mailforspam.com",
    "mailfree.ga",
    "mailfree.gq",
    "mailfree.ml",
    "mailfreeonline.com",
    "mailfs.com",
    "mailguard.me",
    "mailimate.com",
    "mailin8r.com",
    "mailinater.com",
    "mailinator.net",
    "mailinator.org",
    "mailinator.us",
    "mailinator2.com",
    "mailincubator.com",
    "mailismagic.com",
    "mailmate.com",
    "mailme.ir",
    "mailme.lv",
    "mailme24.com",
    "mailmetrash.com",
    "mailmoat.com",
    "mailms.com",
    "mailnull.com",
    "mailorg.org",
    "mailpick.biz",
    "mailproxsy.com",
    "mailquack.com",
    "mailrock.biz",
    "mailsac.com",
    "mailshell.com",
    "mailsiphon.com",
    "mailslite.com",
    "mailtemp.info",
    "mailtome.de",
    "mailtothis.com",
    "mailtrash.net",
    "mailtv.net",
    "mailtv.tv",
    "mailzilla.com",
    "mailzilla.org",
    "mailzilla.orgmbx.cc",
    "mbx.cc",
    "mega.zik.dj",
    "meinspamschutz.de",
    "messagebeamer.de",
    "mezimages.net",
    "ministry-of-silly-walks.de",
    "moburl.com",
    "moncourrier.fr.nf",
    "monemail.fr.nf",
    "monmail.fr.nf",
    "monumentmail.com",
    "msa.minsmail.com",
    "mt2009.com",
    "mx0.wwwnew.eu",
    "mycleaninbox.net",
    "mypartyclip.de",
    "myphantom.com",
    "mysamp.de",
    "myspaceinc.com",
    "myspaceinc.net",
    "myspaceinc.org",
    "myspacepimpedup.com",
    "mytrashmail.com",
    "neomailbox.com",
    "nepwk.com",
    "nervmich.net",
    "nervtansen.de",
    "netmails.com",
    "netmails.net",
    "neverbox.com",
    "no-spam.ws",
    "nobulk.com",
    "noclickemail.com",
    "nogmailspam.info",
    "nomail.xl.cx",
    "nomail2me.com",
    "nomorespamemails.com",
    "nospam.ze.tc",
    "nospam4.us",
    "nospamfor.us",
    "nospammail.net",
    "nothingtoseehere.ca",
    "nowmymail.com",
    "nurfuerspam.de",
    # "nus.edu.sg" — removido: Universidade Nacional de Singapura, não é descartável
    "nwldx.com",
    "objectmail.com",
    "obobbo.com",
    "odnorazovoe.ru",
    "oneoffemail.com",
    "onewaymail.com",
    "oopi.org",
    "ordinaryamerican.net",
    "otherinbox.com",
    "ourklips.com",
    "outlawspam.com",
    "ovpn.to",
    "owlpic.com",
    "pancakemail.com",
    "pimpedupmyspace.com",
    "pjjkp.com",
    "plexolan.de",
    "pookmail.com",
    # "privacy.net" — removido: site de privacidade legítimo, não é descartável
    "privy-mail.de",
    "proxymail.eu",
    "prtnx.com",
    "punkass.com",
    "putthisinyouremail.com",
    # "qq.com" — removido: maior provedor de e-mail da China, não é descartável
    "quickinbox.com",
    "rcpt.at",
    "reallymymail.com",
    "recode.me",
    "recursor.net",
    "reliable-mail.com",
    "rhyta.com",
    "rklips.com",
    "rmqkr.net",
    "royal.net",
    "rppkn.com",
    "rtrtr.com",
    "s0ny.net",
    "safe-mail.net",
    "safersignup.de",
    "safetymail.info",
    "safetypost.de",
    "sandelf.de",
    "saynotospams.com",
    "scatmail.com",
    "schafmail.de",
    "selfdestructingmail.com",
    "sendspamhere.com",
    "sharklasers.com",
    "shieldedmail.com",
    "shiftmail.com",
    "shitmail.me",
    "shortmail.net",
    "sibmail.com",
    "skeefmail.com",
    "slaskpost.se",
    "slipry.net",
    "slopsbox.com",
    "smashmail.de",
    "snoopmail.info",
    "sofimail.com",
    "sofort-mail.de",
    "softpls.asia",
    "sogetthis.com",
    "soodonims.com",
    "spam.la",
    "spam.su",
    "spam4.me",
    "spamavert.com",
    "spambob.com",
    "spambob.net",
    "spambob.org",
    "spambox.info",
    "spambox.irishspringrealty.com",
    "spambox.us",
    "spamcannon.com",
    "spamcannon.net",
    "spamcero.com",
    "spamcorptastic.com",
    "spamcowboy.com",
    "spamcowboy.net",
    "spamcowboy.org",
    "spamday.com",
    "spamex.com",
    "spamfighter.cf",
    "spamfighter.ga",
    "spamfighter.gq",
    "spamfighter.ml",
    "spamfighter.tk",
    "spamfree24.com",
    "spamfree24.de",
    "spamfree24.eu",
    "spamfree24.info",
    "spamfree24.net",
    "spamfree24.org",
    "spamgoes.in",
    "spamherelots.com",
    "spamhereplease.com",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com",
    "spaml.de",
    "spammotel.com",
    "spamobox.com",
    "spamoff.de",
    "spamslicer.com",
    "spamspot.com",
    "spamstack.net",
    "spamthis.co.uk",
    "spamtrail.com",
    "spamtrap.ro",
    "speed.1s.fr",
    "spybox.de",
    "supergreatmail.com",
    "supermailer.jp",
    "superrito.com",
    "superstachel.de",
    "suremail.info",
    "svk.jp",
    "sweetxxx.de",
    "tafmail.com",
    "tagyoureit.com",
    "talkinator.com",
    "tapchicuoihoi.com",
    "teewars.org",
    "teleworm.com",
    "teleworm.us",
    "temp.emeraldcraft.com",
    "temp.headstrong.de",
    "tempail.com",
    "tempalias.com",
    "tempe4mail.com",
    "tempemail.biz",
    "tempemail.co.za",
    "tempemail.com",
    "tempemail.net",
    "tempinbox.co.uk",
    "tempinbox.com",
    "tempmail.eu",
    "tempmail.it",
    "tempmail2.com",
    "tempmaildemo.com",
    "tempmailer.com",
    "tempmailer.de",
    "tempomail.fr",
    "temporarioemail.com.br",
    "temporarily.de",
    "temporaryemail.net",
    "temporaryemail.us",
    "temporaryforwarding.com",
    "temporaryinbox.com",
    "temporarymailaddress.com",
    "tempthe.net",
    "thankyou2010.com",
    "thc.st",
    "thecriminals.com",
    "thejoker5.com",
    "thisisnotmyrealemail.com",
    "thismail.net",
    "throwawayemailaddress.com",
    "tittbit.in",
    "tmail.ws",
    "tmailinator.com",
    "toiea.com",
    "toomail.biz",
    "topranklist.de",
    "tradermail.info",
    "trash2009.com",
    "trash2010.com",
    "trash2011.com",
    "trashdevil.com",
    "trashdevil.de",
    "trashemail.de",
    "trashmail.ws",
    "trashmailer.com",
    "trashymail.com",
    "turual.com",
    "twinmail.de",
    "tyldd.com",
    "uggsrock.com",
    "umail.net",
    "upliftnow.com",
    "uplipht.com",
    "venompen.com",
    "veryreallylemail.com",
    "viditag.com",
    "viewcastmedia.com",
    "viewcastmedia.net",
    "viewcastmedia.org",
    "vomoto.com",
    "vpn.st",
    "vsimcard.com",
    "vubby.com",
    "wasteland.rfc822.org",
    "webemail.me",
    "webm4il.info",
    "weg-werf-email.de",
    "wegwerf-emails.de",
    "wegwerfadresse.de",
    "wegwerfemail.com",
    "wegwerfemail.de",
    "wegwerfmail.de",
    "wegwerfmail.info",
    "wegwerfmail.net",
    "wegwerfmail.org",
    "wilemail.com",
    "willhackforfood.biz",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "wuzup.net",
    "wuzupmail.net",
    "wwwnew.eu",
    "x.ip6.li",
    "xagloo.com",
    "xemaps.com",
    "xents.com",
    "xjoi.com",
    "xmaily.com",
    "xoxy.net",
    "yep.it",
    "yogamaven.com",
    "yuurok.com",
    "zehnminuten.de",
    "zippymail.info",
    "zoaxe.com",
    "zoemail.org",
}


def is_disposable_email(email: str) -> bool:
    """Check whether an email address uses a known disposable domain."""
    try:
        domain = email.rsplit("@", 1)[1].lower().strip()
        return domain in DISPOSABLE_DOMAINS
    except (IndexError, AttributeError):
        return False


def has_valid_mx(domain: str) -> bool:
    """Check if a domain has valid MX or A records (can receive email)."""
    # Trusted domains always pass
    if domain in _TRUSTED_DOMAINS:
        return True

    # Known disposable domains fail immediately
    if domain in DISPOSABLE_DOMAINS:
        return False

    try:
        # Try MX records first (5s timeout to avoid blocking registration)
        answers = dns.resolver.resolve(domain, "MX", lifetime=5)
        return len(answers) > 0
    except (dns.resolver.NoAnswer, dns.resolver.NXDOMAIN, dns.resolver.NoNameservers):
        pass
    except Exception:
        pass

    try:
        # Fallback: check A record (some small domains receive email via A record)
        answers = dns.resolver.resolve(domain, "A", lifetime=5)
        return len(answers) > 0
    except Exception:
        return False


def validate_email_domain(email: str) -> str | None:
    """Validate an email domain. Returns an error message string if invalid, None if OK."""
    try:
        domain = email.rsplit("@", 1)[1].lower().strip()
    except (IndexError, AttributeError):
        return "E-mail inválido."

    if domain in DISPOSABLE_DOMAINS:
        return "Não é possível criar conta com e-mail temporário. Use um e-mail válido."

    if not has_valid_mx(domain):
        return "O domínio do e-mail não existe ou não pode receber mensagens. Use um e-mail válido."

    return None
